/**
 * Represents the database for the Dictionary API app. This database uses the Room persistence library
 * to provide an abstraction layer over SQLite, making it easier to manage the database and its tables.
 * The database is designed to store word entities, which include the word itself and its definitions.
 *
 * @author Jungmin Ju
 * @labSection CST2335 011
 * @creationDate 2024-03-29
 */
package algonquin.cst2335.ju000013;

import androidx.room.Database;
import androidx.room.RoomDatabase;

@Database(entities = {WordEntity.class}, version = 1, exportSchema = false)
public abstract class AppDatabase extends RoomDatabase {
    /**
     * Provides access to the data access object (DAO) for word entities. The DAO defines the methods
     * used for accessing the database.
     *
     * @return The WordDao implementation generated by Room.
     */
    public abstract WordDao wordDao();
}
